# pandas case study

In [1015]:
import pandas as pd
df=pd.read_csv(r"C:\Users\DELL 3400\Downloads\Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

**Q1. Rename the columns of the dataset to 'SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', and 'Species'.**

In [1017]:
df=df.rename(columns={'SepalLengthCm':'SepalLength','SepalWidthCm':'SepalWidth','PetalLengthCm':'PetalLength','PetalWidthCm':'PetalWidth','Species':'species'})
df.columns

Index(['Id', 'SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth',
       'species'],
      dtype='object')

**Q2.**
**a.Set the index of the DataFrame to the 'Species' column.**

**b.Retrieve the first 10 rows of the DataFrame using integer-based indexing**

In [1013]:
#a
df.set_index("species",inplace=True)
df

                 Id  SepalLength  SepalWidth  PetalLength  PetalWidth
species
Iris-setosa       1          5.1         3.5          1.4         0.2
Iris-setosa       2          4.9         3.0          1.4         0.2
Iris-setosa       3          4.7         3.2          1.3         0.2
Iris-setosa       4          4.6         3.1          1.5         0.2
Iris-setosa       5          5.0         3.6          1.4         0.2
...             ...          ...         ...          ...         ...
Iris-virginica  146          6.7         3.0          5.2         2.3
Iris-virginica  147          6.3         2.5          5.0         1.9
Iris-virginica  148          6.5         3.0          5.2         2.0
Iris-virginica  149          6.2         3.4          5.4         2.3
Iris-virginica  150          5.9         3.0          5.1         1.8

[150 rows x 5 columns]

In [1019]:
#b.
set=df.reset_index().head(10)
set

   index  Id  SepalLength  SepalWidth  PetalLength  PetalWidth      species
0      0   1          5.1         3.5          1.4         0.2  Iris-setosa
1      1   2          4.9         3.0          1.4         0.2  Iris-setosa
2      2   3          4.7         3.2          1.3         0.2  Iris-setosa
3      3   4          4.6         3.1          1.5         0.2  Iris-setosa
4      4   5          5.0         3.6          1.4         0.2  Iris-setosa
5      5   6          5.4         3.9          1.7         0.4  Iris-setosa
6      6   7          4.6         3.4          1.4         0.3  Iris-setosa
7      7   8          5.0         3.4          1.5         0.2  Iris-setosa
8      8   9          4.4         2.9          1.4         0.2  Iris-setosa
9      9  10          4.9         3.1          1.5         0.1  Iris-setosa

**Q3.**
**a.Slice the DataFrame to display rows with 'PetalWidth' greater than 2.5.**

**b.Slice the DataFrame to display columns 'SepalLength' and 'SepalWidth' for the first 5 rows.**

In [689]:
#a
#there are no rows with 'PetalWidth' greater than 2.5.
df[df['PetalWidth']>2.5]

Empty DataFrame
Columns: [Id, SepalLength, SepalWidth, PetalLength, PetalWidth, species]
Index: []

In [1021]:
#b
df[0:5][['SepalLength','SepalWidth']]

   SepalLength  SepalWidth
0          5.1         3.5
1          4.9         3.0
2          4.7         3.2
3          4.6         3.1
4          5.0         3.6

In [1023]:
#using iloc
df.iloc[0:5,0:2]

   Id  SepalLength
0   1          5.1
1   2          4.9
2   3          4.7
3   4          4.6
4   5          5.0

In [1025]:
#using loc
df.loc[0:4][['SepalLength','SepalWidth']]

   SepalLength  SepalWidth
0          5.1         3.5
1          4.9         3.0
2          4.7         3.2
3          4.6         3.1
4          5.0         3.6

**Q4.**
**a.Filter the DataFrame to show only rows where 'Species' is 'versicolor'.**

**b.Filter the DataFrame to show rows where 'PetalLength' is greater than 4 and 'SepalWidth' is less than 3.**

In [1028]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [1030]:
#a
df[df['species']=='Iris-versicolor']

     Id  SepalLength  SepalWidth  PetalLength  PetalWidth          species
50   51          7.0         3.2          4.7         1.4  Iris-versicolor
51   52          6.4         3.2          4.5         1.5  Iris-versicolor
52   53          6.9         3.1          4.9         1.5  Iris-versicolor
53   54          5.5         2.3          4.0         1.3  Iris-versicolor
54   55          6.5         2.8          4.6         1.5  Iris-versicolor
55   56          5.7         2.8          4.5         1.3  Iris-versicolor
56   57          6.3         3.3          4.7         1.6  Iris-versicolor
57   58          4.9         2.4          3.3         1.0  Iris-versicolor
58   59          6.6         2.9          4.6         1.3  Iris-versicolor
59   60          5.2         2.7          3.9         1.4  Iris-versicolor
60   61          5.0         2.0          3.5         1.0  Iris-versicolor
61   62          5.9         3.0          4.2         1.5  Iris-versicolor
62   63          6.0         2.2          4.0         1.0  Iris-versicolor
63   64          6.1         2.9          4.7         1.4  Iris-versicolor
64   65          5.6         2.9          3.6         1.3  Iris-versicolor
65   66          6.7         3.1          4.4         1.4  Iris-versicolor
66   67          5.6         3.0          4.5         1.5  Iris-versicolor
67   68          5.8         2.7          4.1         1.0  Iris-versicolor
68   69          6.2         2.2          4.5         1.5  Iris-versicolor
69   70          5.6         2.5          3.9         1.1  Iris-versicolor
70   71          5.9         3.2          4.8         1.8  Iris-versicolor
71   72          6.1         2.8          4.0         1.3  Iris-versicolor
72   73          6.3         2.5          4.9         1.5  Iris-versicolor
73   74          6.1         2.8          4.7         1.2  Iris-versicolor
74   75          6.4         2.9          4.3         1.3  Iris-versicolor
75   76          6.6         3.0          4.4         1.4  Iris-versicolor
76   77          6.8         2.8          4.8         1.4  Iris-versicolor
77   78          6.7         3.0          5.0         1.7  Iris-versicolor
78   79          6.0         2.9          4.5         1.5  Iris-versicolor
79   80          5.7         2.6          3.5         1.0  Iris-versicolor
80   81          5.5         2.4          3.8         1.1  Iris-versicolor
81   82          5.5         2.4          3.7         1.0  Iris-versicolor
82   83          5.8         2.7          3.9         1.2  Iris-versicolor
83   84          6.0         2.7          5.1         1.6  Iris-versicolor
84   85          5.4         3.0          4.5         1.5  Iris-versicolor
85   86          6.0         3.4          4.5         1.6  Iris-versicolor
86   87          6.7         3.1          4.7         1.5  Iris-versicolor
87   88          6.3         2.3          4.4         1.3  Iris-versicolor
88   89          5.6         3.0          4.1         1.3  Iris-versicolor
89   90          5.5         2.5          4.0         1.3  Iris-versicolor
90   91          5.5         2.6          4.4         1.2  Iris-versicolor
91   92          6.1         3.0          4.6         1.4  Iris-versicolor
92   93          5.8         2.6          4.0         1.2  Iris-versicolor
93   94          5.0         2.3          3.3         1.0  Iris-versicolor
94   95          5.6         2.7          4.2         1.3  Iris-versicolor
95   96          5.7         3.0          4.2         1.2  Iris-versicolor
96   97          5.7         2.9          4.2         1.3  Iris-versicolor
97   98          6.2         2.9          4.3         1.3  Iris-versicolor
98   99          5.1         2.5          3.0         1.1  Iris-versicolor
99  100          5.7         2.8          4.1         1.3  Iris-versicolor

In [1034]:
#b
df[(df['PetalLength']>4) & (df['SepalWidth']<3)]

      Id  SepalLength  SepalWidth  PetalLength  PetalWidth          species
54    55          6.5         2.8          4.6         1.5  Iris-versicolor
55    56          5.7         2.8          4.5         1.3  Iris-versicolor
58    59          6.6         2.9          4.6         1.3  Iris-versicolor
63    64          6.1         2.9          4.7         1.4  Iris-versicolor
67    68          5.8         2.7          4.1         1.0  Iris-versicolor
68    69          6.2         2.2          4.5         1.5  Iris-versicolor
72    73          6.3         2.5          4.9         1.5  Iris-versicolor
73    74          6.1         2.8          4.7         1.2  Iris-versicolor
74    75          6.4         2.9          4.3         1.3  Iris-versicolor
76    77          6.8         2.8          4.8         1.4  Iris-versicolor
78    79          6.0         2.9          4.5         1.5  Iris-versicolor
83    84          6.0         2.7          5.1         1.6  Iris-versicolor
87    88          6.3         2.3          4.4         1.3  Iris-versicolor
90    91          5.5         2.6          4.4         1.2  Iris-versicolor
94    95          5.6         2.7          4.2         1.3  Iris-versicolor
96    97          5.7         2.9          4.2         1.3  Iris-versicolor
97    98          6.2         2.9          4.3         1.3  Iris-versicolor
99   100          5.7         2.8          4.1         1.3  Iris-versicolor
101  102          5.8         2.7          5.1         1.9   Iris-virginica
103  104          6.3         2.9          5.6         1.8   Iris-virginica
106  107          4.9         2.5          4.5         1.7   Iris-virginica
107  108          7.3         2.9          6.3         1.8   Iris-virginica
108  109          6.7         2.5          5.8         1.8   Iris-virginica
111  112          6.4         2.7          5.3         1.9   Iris-virginica
113  114          5.7         2.5          5.0         2.0   Iris-virginica
114  115          5.8         2.8          5.1         2.4   Iris-virginica
118  119          7.7         2.6          6.9         2.3   Iris-virginica
119  120          6.0         2.2          5.0         1.5   Iris-virginica
121  122          5.6         2.8          4.9         2.0   Iris-virginica
122  123          7.7         2.8          6.7         2.0   Iris-virginica
123  124          6.3         2.7          4.9         1.8   Iris-virginica
126  127          6.2         2.8          4.8         1.8   Iris-virginica
128  129          6.4         2.8          5.6         2.1   Iris-virginica
130  131          7.4         2.8          6.1         1.9   Iris-virginica
132  133          6.4         2.8          5.6         2.2   Iris-virginica
133  134          6.3         2.8          5.1         1.5   Iris-virginica
134  135          6.1         2.6          5.6         1.4   Iris-virginica
142  143          5.8         2.7          5.1         1.9   Iris-virginica
146  147          6.3         2.5          5.0         1.9   Iris-virginica

**Q5.**
**a.Calculate the minimum 'PetalLength' across all species.**

**b.Calculate the maximum 'SepalWidth' across all species.**

In [1037]:
#a
df['PetalLength'].unique()

array([1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1. , 1.9, 4.7, 4.5, 4.9, 4. ,
       4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5. , 3.8, 3.7,
       5.1, 3. , 6. , 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7, 6.9,
       5.7, 6.4, 5.4, 5.2])

In [1039]:
df['PetalLength'].min()

1.0

In [1041]:
#b
df['SepalWidth'].unique()

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, 4. , 4.4, 3.8, 3.3,
       4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

In [1043]:
df['SepalWidth'].max()

4.4

**Q6.**
**a.Calculate the sum of values along axis=1 (row-wise).**

**b.Calculate the mean of values along axis=0 (column-wise).**

In [1046]:
df[['Id','SepalLength','SepalWidth','PetalLength','PetalWidth']].mean(axis=0)

Id             75.500000
SepalLength     5.843333
SepalWidth      3.054000
PetalLength     3.758667
PetalWidth      1.198667
dtype: float64

In [1048]:
df[['Id','SepalLength','SepalWidth','PetalLength','PetalWidth']].sum(axis=1)

0       11.2
1       11.5
2       12.4
3       13.4
4       15.2
       ...
145    163.2
146    162.7
147    164.7
148    166.3
149    165.8
Length: 150, dtype: float64

**Q7. Add a new column 'PetalArea' calculated as the product of 'PetalLength' and 'PetalWidth'.**

In [1051]:
df['PetalArea']=df['PetalLength']*df['PetalWidth']
df

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,species,PetalArea
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0.28
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0.28
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0.26
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0.30
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0.28
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.96
146,147,6.3,2.5,5.0,1.9,Iris-virginica,9.50
147,148,6.5,3.0,5.2,2.0,Iris-virginica,10.40
148,149,6.2,3.4,5.4,2.3,Iris-virginica,12.42
149,150,5.9,3.0,5.1,1.8,Iris-virginica,9.18

**Q8. Convert the 'SepalLength' column to float dtype using astype.**

In [1054]:
df['SepalLength'].astype('float')

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLength, Length: 150, dtype: float64

In [1056]:
df

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,species,PetalArea
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0.28
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0.28
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0.26
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0.30
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0.28
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.96
146,147,6.3,2.5,5.0,1.9,Iris-virginica,9.50
147,148,6.5,3.0,5.2,2.0,Iris-virginica,10.40
148,149,6.2,3.4,5.4,2.3,Iris-virginica,12.42
149,150,5.9,3.0,5.1,1.8,Iris-virginica,9.18

**Q9. Query the DataFrame to show rows where 'PetalLength' is greater than 'SepalLength'.**

In [1059]:
df[df['PetalLength']>df['SepalLength']]

Empty DataFrame
Columns: [Id, SepalLength, SepalWidth, PetalLength, PetalWidth, species, PetalArea]
Index: []

**Q10. Apply a function to calculate the difference between 'PetalLength' and 'SepalLength' for each row.**

In [1062]:
def diff(row):
    return row['PetalLength']-row['SepalLength']
df['difference']=df.apply(diff,axis=1)
df

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,species,PetalArea,difference
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0.28,-3.7
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0.28,-3.5
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0.26,-3.4
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0.30,-3.1
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0.28,-3.6
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.96,-1.5
146,147,6.3,2.5,5.0,1.9,Iris-virginica,9.50,-1.3
147,148,6.5,3.0,5.2,2.0,Iris-virginica,10.40,-1.3
148,149,6.2,3.4,5.4,2.3,Iris-virginica,12.42,-0.8
149,150,5.9,3.0,5.1,1.8,Iris-virginica,9.18,-0.8

In [1064]:
df['difference']=df.apply(lambda row:row['PetalLength']-row['SepalLength'],axis=1)
df

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,species,PetalArea,difference
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0.28,-3.7
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0.28,-3.5
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0.26,-3.4
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0.30,-3.1
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0.28,-3.6
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.96,-1.5
146,147,6.3,2.5,5.0,1.9,Iris-virginica,9.50,-1.3
147,148,6.5,3.0,5.2,2.0,Iris-virginica,10.40,-1.3
148,149,6.2,3.4,5.4,2.3,Iris-virginica,12.42,-0.8
149,150,5.9,3.0,5.1,1.8,Iris-virginica,9.18,-0.8

**Q11.** 
**a.Find the top 3 rows with the largest 'PetalLength'.**

**b.Find the top 3 rows with the smallest 'SepalWidth'.**

In [717]:
df['PetalLength'].max()

6.9

In [715]:
#a
max_3=df.sort_values(by='PetalLength',ascending=False)
max_3.head(3)

      Id  SepalLength  SepalWidth  PetalLength  PetalWidth         species
118  119          7.7         2.6          6.9         2.3  Iris-virginica
122  123          7.7         2.8          6.7         2.0  Iris-virginica
117  118          7.7         3.8          6.7         2.2  Iris-virginica

In [1068]:
#b
min_3=df.sort_values(by='SepalWidth',ascending=True)
min_3.head(3)

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,species,PetalArea,difference
60,61,5.0,2.0,3.5,1.0,Iris-versicolor,3.5,-1.5
62,63,6.0,2.2,4.0,1.0,Iris-versicolor,4.0,-2.0
119,120,6.0,2.2,5.0,1.5,Iris-virginica,7.5,-1.0

**Q12.**
**a.Sort the DataFrame by 'PetalWidth' in ascending order.**

**b.Sort the DataFrame by 'SepalLength' in descending order**

In [735]:
#a
petalw=df.sort_values(by='PetalWidth',ascending=True)
petalw

      Id  SepalLength  SepalWidth  PetalLength  PetalWidth         species
32    33          5.2         4.1          1.5         0.1     Iris-setosa
13    14          4.3         3.0          1.1         0.1     Iris-setosa
37    38          4.9         3.1          1.5         0.1     Iris-setosa
9     10          4.9         3.1          1.5         0.1     Iris-setosa
12    13          4.8         3.0          1.4         0.1     Iris-setosa
..   ...          ...         ...          ...         ...             ...
140  141          6.7         3.1          5.6         2.4  Iris-virginica
114  115          5.8         2.8          5.1         2.4  Iris-virginica
100  101          6.3         3.3          6.0         2.5  Iris-virginica
144  145          6.7         3.3          5.7         2.5  Iris-virginica
109  110          7.2         3.6          6.1         2.5  Iris-virginica

[150 rows x 6 columns]

In [739]:
#b
sepall=df.sort_values(by='SepalLength',ascending=False)
sepall

      Id  SepalLength  SepalWidth  PetalLength  PetalWidth         species
131  132          7.9         3.8          6.4         2.0  Iris-virginica
135  136          7.7         3.0          6.1         2.3  Iris-virginica
122  123          7.7         2.8          6.7         2.0  Iris-virginica
117  118          7.7         3.8          6.7         2.2  Iris-virginica
118  119          7.7         2.6          6.9         2.3  Iris-virginica
..   ...          ...         ...          ...         ...             ...
41    42          4.5         2.3          1.3         0.3     Iris-setosa
42    43          4.4         3.2          1.3         0.2     Iris-setosa
38    39          4.4         3.0          1.3         0.2     Iris-setosa
8      9          4.4         2.9          1.4         0.2     Iris-setosa
13    14          4.3         3.0          1.1         0.1     Iris-setosa

[150 rows x 6 columns]